# Generated by Django 3.2.16 on 2022-11-22 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_imageplace'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imageplace',
            options={'verbose_name_plural': 'Картинки'},
        ),
        migrations.AlterModelOptions(
            name='place',
            options={'verbose_name_plural': 'Локации'},
        ),
        migrations.AlterField(
            model_name='imageplace',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
