# Generated by Django 3.2.16 on 2022-11-23 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0004_auto_20221122_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageplace',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='places', to='places.place'),
        ),
    ]
