# Generated by Django 3.2.16 on 2022-11-24 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0006_alter_imageplace_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageplace',
            name='position',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
