# Generated by Django 4.1.3 on 2022-11-27 16:09

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0007_imageplace_position'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imageplace',
            options={'ordering': ['position'], 'verbose_name_plural': 'Картинки'},
        ),
        migrations.AlterField(
            model_name='place',
            name='coordinate_lat',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='coordinate_lng',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='description_long',
            field=tinymce.models.HTMLField(null=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='description_short',
            field=models.TextField(null=True),
        ),
    ]
