# Generated by Django 4.1.3 on 2022-11-27 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0008_alter_imageplace_options_alter_place_coordinate_lat_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imageplace',
            name='title',
        ),
    ]
