# Generated by Django 4.1.3 on 2022-11-29 16:23

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0009_remove_imageplace_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='coordinate_lat',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='place',
            name='coordinate_lng',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='place',
            name='description_long',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='description_short',
            field=models.TextField(blank=True, null=True),
        ),
    ]
