# Generated by Django 4.1.3 on 2022-11-30 18:58

from django.db import migrations, models

import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0010_alter_place_coordinate_lat_and_more'),
    ]

    operations = [
        migrations.RenameField('Place', 'coordinate_lng', 'lng'),
        migrations.RenameField('Place', 'coordinate_lat', 'lat'),
        migrations.AlterField('Place', 'lng', models.FloatField()),
        migrations.AlterField('Place', 'lat', models.FloatField()),
        migrations.AlterField('Place', 'description_short', models.TextField(blank=True)),
        migrations.AlterField('Place', 'description_long', tinymce.models.HTMLField(blank=True)),
    ]
